### ISSUE TITLE
[Bug] CICDs are not starting when YAML pushed

### ISSUE THREAD

**Issue by dspv** [kuttleio/terraform-aws-environment#82]
## Story
When we create a new Env and put GH Actions YAML into services' repositories, the CICD (Github Actions) are not starting.

#### Just to remove
```
    paths-ignore:
    - '.github/workflows/**'
```

#### From cicd.tpl.yaml
```
on:
  push:
    branches:
    - '${ deploy_branch }'
    paths-ignore:
    - '.github/workflows/**'
  workflow_dispatch:
```

## Link
https://github.com/kuttleio/terraform-aws-environment/blob/1635aa5c03d7cb79b56099776733de8f554ddb9e/cicd.tpl.yaml#L7
